// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkbYnbrbTwpZ9Q818vzEc8HJZ-XvCQlQ',
    appId: '1:1071717309843:web:c6ff65310a090f7a681c66',
    messagingSenderId: '1071717309843',
    projectId: 'final-project-19aa1',
    authDomain: 'final-project-19aa1.firebaseapp.com',
    storageBucket: 'final-project-19aa1.appspot.com',
    measurementId: 'G-MCTET69XEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNq_sJWGJDZI_D_xhH_mz_cUJb-jfX3I',
    appId: '1:1071717309843:android:1edba9c946c13572681c66',
    messagingSenderId: '1071717309843',
    projectId: 'final-project-19aa1',
    storageBucket: 'final-project-19aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6dzYK41d6gGhBPvdFgRsDFcE6y6zEb8',
    appId: '1:1071717309843:ios:07f5236906f65495681c66',
    messagingSenderId: '1071717309843',
    projectId: 'final-project-19aa1',
    storageBucket: 'final-project-19aa1.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6dzYK41d6gGhBPvdFgRsDFcE6y6zEb8',
    appId: '1:1071717309843:ios:79e9a291d5c167a3681c66',
    messagingSenderId: '1071717309843',
    projectId: 'final-project-19aa1',
    storageBucket: 'final-project-19aa1.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
